[package]
name = "arceon-crypto"
version = "0.1.0"
edition = "2021"
description = "Cryptographic utilities for Arceon"

[dependencies]
serde = { workspace = true }
anyhow = { workspace = true }
ed25519-dalek = { workspace = true }
sha2 = { workspace = true }
